### ISSUE TITLE
JQuery Versioning

### ISSUE THREAD

**Issue by HimanshuGenpact** [mendix/TooltipLink#3]
Hi Team,

I am using this widget in one of my application and this widget is using Jquery version 1.11.2 which is vulnerable to XSS scripting. So, I request you to update the Jquery version in this widget and Version should be greater than 1.12.0.

Waiting for your response..

**Comment by JelteMX** [comment]
I am working on updating a couple of widgets in terms of jQuery versions, starting with CKEditor. I will create an update for TooltipLink this week.

**Comment by sowmyarepala** [comment]
Hi,
Is this update done?

**Comment by sowmyarepala** [comment]
Hi Team,
Could anyone please tell me if jQuery update is done for this widget?

**Comment by RoelandSalij** [comment]
Hi Sowmya,
Unfortunately Jelte has not been able to finish his update for this widget.
From our previous conversation outside this issue thread I understand that you want to go ahead and create a pull request. (https://github.com/mendix/TooltipLink/pulls)
Is that correct?

**Comment by sowmyarepala** [comment]
Hi Salij,

Yes as its taking some more time for Jelte to do this update, if you provide me access to create branch and commit changes I will do this update from my side and let you know so that you can upload this to Mendix AppStore.

**Comment by JelteMX** [comment]
You can create a fork if you want, there are multiple tutorials on that.

When it comes to this XSS vulnerability, it is not applicable in Mendix. This only applies to AJAX requests made from jQuery, which is not done here. More information can be found [here](https://snyk.io/vuln/npm:jquery:20150627).

I am moving this issue to a lower prio as I have other projects I am working on

**Comment by JelteMX** [comment]
Well, this is embarrassing. TooltipLink [does not use jQuery](https://github.com/mendix/TooltipLink/search?q=jquery&unscoped_q=jquery). Are you sure you are looking at the same widget? I am closing this issue.
